Models/DISR190002/DISR190002.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AI070.Models.DISR190002Master
{
    public class DISR190002
    {
        public string ID { get; set; }
        public string ID_SEISAN { get; set; }
        public string CODE { get; set; }
        public string OTHER_LOTNO { get; set; }
        public string ID_KOTEI { get; set; }
        public string ID_JUCHUCHUBAN { get; set; }
        public string ID_SEISANRENBAN { get; set; }


        public string TIME_CD { get; set; }
        public string TIME_VAL { get; set; }

        // untuk combobox Status
        public string STS_CD { get; set; }
        public string STS_VAL { get; set; }
        public string STACK { get; set; }
        public string LINE_STS { get; set; }

    }

}

Models/DISR190002/DISR190002Master.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AI070.Models.DISR190002Master
{
    public class DISR190002Master
    {
        public string ID { get; set; }
        public string ID_SEISAN { get; set; }
        public string ID_SEIHIN { get; set; }
        public string ID_HINMOKU { get; set; }
        public string CODE { get; set; }
        public string KCODE { get; set; }
        public string OTHER_LOTNO { get; set; }
        public string ID_KOTEI { get; set; }
        public string ID_JUCHUCHUBAN { get; set; }
        public string ID_SEISANRENBAN { get; set; }
        public string CONT { get; set; }
        public string AMNT_KEIKAKU_2 { get; set; }


        public string EXECUTOR { get; set; }
        public Int32 ROW_NUM { get; set; }
        public Int32 Number { get; set; }
        public string DELETE_DATA { get; set; }
        public string STACK { get; set; }
        public string LINE_STS { get; set; }

    }

}

Controllers/DISR190002/DISR190002Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Xml;
using Toyota.Common.Web.Platform;
using AI070.Models;
using AI070.Models.Shared;
using AI070.Models.DISR190002Master;
using System.Security.Cryptography;
using System.Text;
using Rotativa.Options;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Printing;
//using Neodynamic.SDK.Web;

namespace AI070.Controllers
{
    public class DISR190002Controller : PageController
    {
        ResultMessage rm = new ResultMessage();
        Message M = new Message();
        DISR190002Repository R = new DISR190002Repository();
        User U = new User();
        string username;
        string MESSAGE_TXT;
        string MESSAGE_TYPE;

        protected override void Startup()
        {
            try
            {
                Settings.Title = "Label Chukan";
                ViewData["Title"] = Settings.Title;
                GetDataHeader();
            }
            catch (Exception e)
            {
                Response.Redirect("authorized");
            }
        }

        #region Search Data
        public ActionResult Search_Data(int start, int display, string DATA_ID, string ID_SEISAN, string ID_HINMOKU)
        {
            //Buat Paging//
            PagingModel_DISR190002 pg = new PagingModel_DISR190002(R.getCountDISR190002(DATA_ID, ID_SEISAN, ID_HINMOKU), start, display);

            //Munculin Data ke Grid//
            List<DISR190002Master> List = R.getDataDISR190002(pg.StartData, pg.EndData, ID_SEISAN, ID_HINMOKU).ToList();
            ViewData["DataDISR190002"] = List;
            ViewData["PagingDISR190002"] = pg;
            return PartialView("Datagrid_Data", pg.CountData);
        }
        #endregion    
        
        #region Search Data Item Code
        public ActionResult Search_Data_ItemCode(int start, int display, string DATA_ID, string CODE)
        {
            //Buat Paging//
            PagingModel_DISR190002 pg = new PagingModel_DISR190002(R.getCountDISR190002_ItemCode(DATA_ID, CODE), start, display);

            //Munculin Data ke Grid//
            List<DISR190002Master> List = R.getDataDISR190002_ItemCode(pg.StartData, pg.EndData, CODE).ToList();
            ViewData["DataDISR190002"] = List;
            ViewData["PagingDISR190002"] = pg;
            return PartialView("Datagrid_Data_Similar", pg.CountData);
        }
        #endregion        

        public ActionResult GenerateMessage(string MSG_ID, string p_PARAM1, string p_PARAM2, string p_PARAM3, string p_PARAM4)
        {
            try
            {
                M.MSG_ID = MSG_ID;
                M.p_PARAM1 = p_PARAM1;
                M.p_PARAM2 = p_PARAM2;
                M.p_PARAM3 = p_PARAM3;
                M.p_PARAM4 = p_PARAM4;
                var res = M.getMessageTextWithFunctionSQL(M);
                MESSAGE_TXT = res[0].MSG_TEXT;
                MESSAGE_TYPE = res[0].MSG_TYPE;
            }
            catch (Exception M)
            {
                MESSAGE_TXT = M.Message.ToString();
                MESSAGE_TYPE = "Err";
            }
            return Json(new { MESSAGE_TXT, MESSAGE_TYPE }, JsonRequestBehavior.AllowGet);
        }

        #region Data Header
        public void GetDataHeader()
        {
            try
            {
                ViewData["EXECUTOR"] = R.getExecutor();  
                username = Lookup.Get<Toyota.Common.Credential.User>().Username.ToString();
                ViewData["UserInfo"] = UserInfoRepository.Instance.GetUserInfo(username);
            }
            catch (Exception M)
            {
                M.Message.ToString();
            }
        }
        #endregion        

        //#region Add New        
        //public ActionResult ADD_NEW(
        //    DateTime target_date,
        //    decimal target_amount,
        //    decimal target_print,
        //    decimal target_amount_jam_ke_1,
        //    decimal target_amount_jam_ke_2,
        //    decimal target_amount_jam_ke_3,
        //    decimal targer_amount_jam_ke_4,
        //    decimal target_amount_jam_ke_5,
        //    decimal target_amount_jam_ke_6,
        //    decimal target_amount_jam_ke_7,
        //    decimal target_amount_jam_ke_8,
        //    decimal target_amount_jam_ke_9,
        //    decimal terget_amount_jam_ke_10,
        //    decimal target_amount_jam_ke_11,
        //    decimal target_amount_jam_ke_12,
        //    decimal target_amount_jam_ke_13,
        //    decimal target_amount_jam_ke_14,
        //    decimal target_amount_jam_ke_15_16_istirahat,
        //    decimal target_amount_jam_ke_17,
        //    decimal target_amount_jam_ke_18,
        //    decimal target_amount_jam_ke_19,
        //    decimal target_amount_jam_ke_20,
        //    decimal target_amount_jam_ke_21,
        //    decimal target_amount_jam_ke_22
        //    )
        //{
        //    string sts = null;
        //    string message = null;
        //    username = Lookup.Get<Toyota.Common.Credential.User>().Username.ToString();
        //    //string pass = EncryptPassword(PASSWORD);
        //    try
        //    {
        //        string username = Lookup.Get<Toyota.Common.Credential.User>().Username;
        //        var Exec = DISR190002Repository.Create(
        //             target_date,
        //             target_amount,
        //             target_amount_jam_ke_1,
        //             target_amount_jam_ke_2,
        //             target_amount_jam_ke_3,
        //             targer_amount_jam_ke_4,
        //             target_amount_jam_ke_5,
        //             target_amount_jam_ke_6,
        //             target_amount_jam_ke_7,
        //             target_amount_jam_ke_8,
        //             target_amount_jam_ke_9,
        //             terget_amount_jam_ke_10,
        //             target_amount_jam_ke_11,
        //             target_amount_jam_ke_12,
        //             target_amount_jam_ke_13,
        //             target_amount_jam_ke_14,
        //             target_amount_jam_ke_15_16_istirahat,
        //             target_amount_jam_ke_17,
        //             target_amount_jam_ke_18,
        //             target_amount_jam_ke_19,
        //             target_amount_jam_ke_20,
        //             target_amount_jam_ke_21,
        //             target_amount_jam_ke_22,
        //            username);
        //        sts = Exec[0].STACK;

        //        if (Exec[0].LINE_STS == "DUPLICATE")
        //        {
        //            var res = M.get_default_message("MWP004", "Master Qty Amount Target", "", "");
        //            message = res[0].MSG_TEXT;
        //        }
        //        else if (Exec[0].STACK == "TRUE")
        //        {
        //            var res = M.get_default_message("MWP001", "Master Qty Amount Target", "", "");
        //            message = res[0].MSG_TEXT;
        //        }
        //        else
        //        {
        //            message = Exec[0].LINE_STS;
        //        }
        //    }
        //    catch (Exception M)
        //    {
        //        sts = "false";
        //        message = M.Message.ToString();
        //    }
        //    return Json(new { sts, message }, JsonRequestBehavior.AllowGet);
        //}
        //#endregion

        //#region Update Data
        //public ActionResult Update_Data(string DATA)
        //{
        //    string stsRespon;
        //    var sts = new object();
        //    var message = new object();
        //    username = Lookup.Get<Toyota.Common.Credential.User>().Username.ToString();
        //    try
        //    {
        //        string username = Lookup.Get<Toyota.Common.Credential.User>().Username;
        //        var Datas = DATA.Split(',');
        //        string ID = Datas[0];
        //        DateTime target_date = Datas[1];
        //        decimal target_amount = Datas[2];
        //        decimal target_print = Datas[3];
        //        decimal target_amount_jam_ke_1 = Datas[4];
        //        decimal target_amount_jam_ke_2 = Datas[5];
        //        decimal target_amount_jam_ke_3 = Datas[6];
        //        decimal targer_amount_jam_ke_4 = Datas[7];
        //        decimal target_amount_jam_ke_5 = Datas[8];
        //        decimal target_amount_jam_ke_6 = Datas[9];
        //        decimal target_amount_jam_ke_7 = Datas[10];
        //        decimal target_amount_jam_ke_8 = Datas[11];
        //        decimal target_amount_jam_ke_9 = Datas[12];
        //        decimal terget_amount_jam_ke_10 = Datas[13];
        //        decimal target_amount_jam_ke_11 = Datas[14];
        //        decimal target_amount_jam_ke_12 = Datas[15];
        //        decimal target_amount_jam_ke_13 = Datas[16];
        //        decimal target_amount_jam_ke_14 = Datas[17];
        //        decimal target_amount_jam_ke_15_16_istirahat = Datas[18];
        //        decimal target_amount_jam_ke_17 = Datas[19];
        //        decimal target_amount_jam_ke_18 = Datas[20];
        //        decimal target_amount_jam_ke_19 = Datas[21];
        //        decimal target_amount_jam_ke_20 = Datas[22];
        //        decimal target_amount_jam_ke_21 = Datas[23];
        //        decimal target_amount_jam_ke_22 = Datas[25];

        //        string STATUS = "1";
        //        var EXEC = R.Update_Data(
        //            ID,
        //            target_date,
        //            target_amount,
        //            target_amount_jam_ke_1,
        //            target_amount_jam_ke_2,
        //            target_amount_jam_ke_3,
        //            targer_amount_jam_ke_4,
        //            target_amount_jam_ke_5,
        //            target_amount_jam_ke_6,
        //            target_amount_jam_ke_7,
        //            target_amount_jam_ke_8,
        //            target_amount_jam_ke_9,

Controllers/DISR190002/WebClientPrintAPIController.cs
using Neodynamic.SDK.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AI070.Controllers.DISR190002
{
    public class WebClientPrintAPIController : Controller
    {
        // GET: WebClientPrintAPI
        [AllowAnonymous]
        public void ProcessRequest()
        {
            //get session ID
            string sessionID = (HttpContext.Request["sid"] != null ? HttpContext.Request["sid"] : null);

            //get Query String
            string queryString = HttpContext.Request.Url.Query;

            try
            {
                //Determine and get the Type of Request 
                RequestType prType = WebClientPrint.GetProcessRequestType(queryString);

                if (prType == RequestType.GenPrintScript ||
                    prType == RequestType.GenWcppDetectScript)
                {
                    //Let WebClientPrint to generate the requested script
                    byte[] script = WebClientPrint.GenerateScript(Url.Action("ProcessRequest", "WebClientPrintAPI", null, HttpContext.Request.Url.Scheme), queryString);

                    HttpContext.Response.ContentType = "text/javascript";
                    HttpContext.Response.BinaryWrite(script);
                    HttpContext.Response.End();
                }
                else if (prType == RequestType.ClientSetWcppVersion)
                {
                    //This request is a ping from the WCPP utility
                    //so store the session ID indicating it has the WCPP installed
                    //also store the WCPP Version if available
                    string wcppVersion = HttpContext.Request["wcppVer"];
                    if (string.IsNullOrEmpty(wcppVersion))
                        wcppVersion = "1.0.0.0";

                    HttpContext.Application.Set(sessionID + "wcppInstalled", wcppVersion);
                }
                else if (prType == RequestType.ClientSetInstalledPrinters)
                {
                    //WCPP Utility is sending the installed printers at client side
                    //so store this info with the specified session ID
                    string printers = HttpContext.Request["printers"];
                    if (string.IsNullOrEmpty(printers) == false)
                        printers = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(printers));

                    HttpContext.Application.Set(sessionID + "printers", printers);

                }
                else if (prType == RequestType.ClientSetInstalledPrintersInfo)
                {
                    //WCPP Utility is sending the client installed printers with detailed info
                    //so store this info with the specified session ID
                    //Printers Info is in JSON format
                    string printersInfo = HttpContext.Request.Form["printersInfoContent"];

                    if (string.IsNullOrEmpty(printersInfo) == false)
                        printersInfo = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(printersInfo));

                    HttpContext.Application.Set(sessionID + "printersInfo", printersInfo);


                }
                else if (prType == RequestType.ClientGetWcppVersion)
                {
                    //return the WCPP version for the specified sid if any
                    bool sidWcppVersion = (HttpContext.Application.Get(sessionID + "wcppInstalled") != null);

                    HttpContext.Response.ContentType = "text/plain";
                    HttpContext.Response.Write((sidWcppVersion ? HttpContext.Application.Get(sessionID + "wcppInstalled") : ""));
                    HttpContext.Response.End();

                }
                else if (prType == RequestType.ClientGetInstalledPrinters)
                {
                    //return the installed printers for the specified sid if any
                    bool sidHasPrinters = (HttpContext.Application.Get(sessionID + "printers") != null);

                    HttpContext.Response.ContentType = "text/plain";
                    HttpContext.Response.Write((sidHasPrinters ? HttpContext.Application.Get(sessionID + "printers") : ""));
                    HttpContext.Response.End();
                }
                else if (prType == RequestType.ClientGetInstalledPrintersInfo)
                {
                    //return the installed printers with detailed info for the specified Session ID (sid) if any
                    bool sidHasPrinters = (HttpContext.Application[sessionID + "printersInfo"] != null);

                    HttpContext.Response.ContentType = "text/plain";
                    HttpContext.Response.Write(sidHasPrinters ? HttpContext.Application[sessionID + "printersInfo"] : "");

                }

            }
            catch (Exception ex)
            {
                HttpContext.Response.StatusCode = 500;
                HttpContext.Response.ContentType = "text/plain";
                HttpContext.Response.Write(ex.Message + " - StackTrace: " + ex.StackTrace);
                HttpContext.Response.End();
            }


        }
    }
}

Views/DISR190002/DISR190002.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("SearchCriteria")
@Html.Partial("Datagrid_Data")

@Html.Partial("Javascript")
@Html.Partial("PopupForm")
@Html.Partial("ModalForm")

Views/DISR190002/Input Form.cshtml
@using AI070.Models;
@using AI070.Models.Shared;
@using AI070.Models.DISR190002Master;
@using System.Data;
@{
    List<DISR190002Master> DataWP = (List<DISR190002Master>)ViewData["DataDISR190002"];
    List<DISR190002Similar_Type> List_Tipe_Similar = (List<DISR190002Similar_Type>)ViewData["DataSimilar"];
    List<DISR190002Master> List_All_Tipe = (List<DISR190002Master>)ViewData["all_tipe"];
    //List<DISR190002Master> List_Printer = (List<DISR190002Master>)ViewData["printers"];
    List<string> List_Printer = (List<string>)ViewData["printers"];

}



<div class="col-md-4" style="position: relative;">
    <!------------------- Form Input Print ------------>
    <div class="col-xs-12 col-sm-12" style="overflow: hidden;" id="">
        <p style="width: 100%; color: blue; text-decoration: underline;">
            <b>Form Input</b>
        </p>
        <div class="col-xs-12 col-md-12" style="border: 1px solid #eaeaea; padding: 10px 5px 10px 5px;">
            <div class="col-md-12" style="">
                <div class="col-md-12">
                    <label>Pilih Printer : </label>
                    <div id="installedPrinters">
                        <select class="form-control select2" name="installedPrinterName" id="selectPrinter"></select>
                    </div>
                </div>
            </div>
            @*<div class="col-md-12" style="">
                    <div class="col-md-12">
                        <label>Pilih File : </label>
                        <input id="input-local-xls-file" type="file" />
                    </div>
                </div>*@
            <!--<div class="col-md-12" style="">
                <div class="col-md-12">
                    <div id="loadPrinters">
                        Click to load and select one of the installed printers!
                        <br />-->
            @*<input type="button" onclick="javascript:jsWebClientPrint.getPrinters();" value="Load installed printers..." />*@
            <!--<a onclick="javascript: jsWebClientPrint.getPrinters();" class="btn btn-success">Get Printers Info...</a>
                        <br /><br />
                    </div>
                    <div id="installedPrinters" style="visibility:hidden">
                        <label for="installedPrinterName">Select an installed Printer:</label>
                        <select name="installedPrinterName" id="installedPrinterName"></select>
                    </div>
                </div>
            </div>-->
            @*<div class="col-md-12" style="margin-top: 15px;">
                    <div class="col-md-12">
                        <label>Pilih Printer : </label>
                        <select class="form-control select2" id="selectPrinter">
                            <option value="" selected="selected" style="font-style: italic; color: gray"> --- Pilih Printer --- </option>
                            @{
                                if (List_Printer != null)
                                {
                                    if (List_Printer.Count() > 0)
                                    {
                                        foreach (string printer_name in List_Printer)
                                        {
                                            <option value="@printer_name">@printer_name</option>
                                        }
                                    }
                                }
                            }
                        </select>
                    </div>
                </div>*@
            <div class="col-md-12" style="margin-top: 15px;">
                <div class="col-md-6">
                    <label>ID Produksi</label>
                    <input type="text" autocomplete="off" class="form-control" id="searchIDSeisan" oninput="eventAutoSearchTyping()" maxlength="20">
                </div>
                <div class="col-md-6">
                    <label>DMC TYPE</label>
                    <input autocomplete="off" id="editIDHinmoku" readonly type="text" class="form-control" />
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;">
                <div class="col-md-6">
                    <input type="checkbox" id="checkSimilar" style="width:15px; height:15px; cursor:pointer"><label style="margin-left:5px">SIMILAR</label>
                    <input type="text" autocomplete="off" class="form-control" id="editSimilar">
                </div>
                <div class="col-md-6">
                    <input type="checkbox" id="checkSearchSimilar" style="width:15px; height:15px; cursor:pointer"><label style="margin-left:5px">Search Similar</label>
                    <select class="form-control select2" id="selectSimilarTipe">
                        <option value="" selected="selected" style="font-style: italic; color: gray"> --- Search --- </option>
                        @{
                            if (List_All_Tipe != null)
                            {
                                if (List_All_Tipe.Count() > 0)
                                {
                                    foreach (DISR190002Master item in List_All_Tipe)
                                    {
                                        <option value="@item.CODE">@item.CODE</option>
                                    }
                                }
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;">
                <div class="col-md-6">
                    <label style="margin-top:5px">LOT</label>
                    <input id="editLot" required type="text" readonly class="form-control" />
                </div>
                <div class="col-md-6" id="Display_LotIhouse">
                    @*<input type="checkbox" id="checkLotIhouse" style="width:15px; height:15px; cursor:pointer">*@<label style="margin-left:5px">LOT IHOUSE</label>
                    <input type="text" autocomplete="off" class="form-control" id="editLotIhouse">
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;">
                <div class="col-md-6">
                    <label>QTY/PACK</label>
                    <input autocomplete="off" id="editQty" required type="number" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label>ADM IT</label>
                    <input type="text" autocomplete="off" class="form-control" id="editADM_IT">
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;">
                <div class="col-md-6">
                    <label>OPT. PRESS/ SCRIBE</label>
                    <input autocomplete="off" id="editOpt_Press" required type="text" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label>OPT. LAM/ PACKING</label>
                    <input autocomplete="off" id="editOpt_Lam" type="text" class="form-control">
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;">
                <div class="col-md-6">
                    <label>JENIS TINTA DOT</label>
                    <input autocomplete="off" id="editJenisTintaDot" required type="text" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label>QTY PRINT</label>
                    <input autocomplete="off" id="editQtyPrint" type="number" class="form-control">
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;" id="Display_GlassBuwon">
                <div class="col-md-6">
                    <input type="checkbox" id="editGlassBuwon">
                    <label>GLASS BUWON</label>
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;" id="Display_AfterLaminate">
                <div class="col-md-6">
                    <input type="checkbox" id="editAfterLaminate">
                    <label>AFTER LAMINATE</label>
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;">
                <div class="col-md-6">
                    <input type="checkbox" class="chkboxname" id="editSpecialPrint">
                    <b><u>SPECIAL PRINT</u></b>
                </div>
            </div>
            <div class="col-md-12" style="margin-top: 15px;">
                <div class="col-md-12" id="display_special_print">
                    @*<input type="checkbox" class="chkboxname" id="checkPengganti">*@
                    <input type="radio" id="checkPengganti" name="chooseSpecialPrint">
                    <label for="checkPengganti">PENGGANTI</label>
                    <input id="editPengganti1" type="text" style="width:60px; height:25px"> /
                    <input id="editPengganti2" type="text" style="width:60px; height:25px">

                    <br />
                    <input type="radio" id="chekTambahan" name="chooseSpecialPrint">
                    <label for="chekTambahan">TAMBAHAN</label>
                    <input id="editTambahan1" type="number" style="width:60px; height:25px"> /
                    <input id="editTambahan2" type="number" style="width:60px; height:25px"> /
                    <input id="editTambahan3" type="text" style="width:60px; height:25px">
                </div>
            </div>

            <div class="col-md-12" style="margin-top: 20px">
                <div class="col-md-6" style="text-align: right">
                    <button type="button" onclick="clear_search()" class="btn btn-grey btn-sm" id="btn_clear" style="width: 80px;"><i class="fa fa-eraser"></i> Clear</button>
                </div>
                <div class="col-md-6" style="text-align: left">
                    <button onclick="print_check()" class="btn btn-primary btn-sm" style="width: 85px;"><i class="fa fa-print"></i> Print</button>
                    @*<button onclick="doPrinting()" class="btn btn-primary btn-sm" style="width: 85px;"><i class="fa fa-print"></i> Print_File</button>*@
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //WebSocket settings (Get Printer)
    JSPM.JSPrintManager.auto_reconnect = true;
    JSPM.JSPrintManager.start();
    JSPM.JSPrintManager.WS.onStatusChanged = function () {
        //get client installed printers
        if (jspmWSStatus()) {
            //get client installed printers
            JSPM.JSPrintManager.getPrinters().then(function (printersList) {
                clientPrinters = printersList;
                var options = '';
                for (var i = 0; i < clientPrinters.length; i++) {
                    options += '<option>' + clientPrinters[i] + '</option>';
                }
                $('#selectPrinter').html(options);
            });
        }
    };

    //Check JSPM WebSocket status
    function jspmWSStatus() {
        if (JSPM.JSPrintManager.websocket_status == JSPM.WSStatus.Open)
            return true;
        else if (JSPM.JSPrintManager.websocket_status == JSPM.WSStatus.Closed) {
            console.warn('JSPrintManager (JSPM) is not installed or not running! Download JSPM Client App from https://neodynamic.com/downloads/jspm');
            return false;
        }
        else if (JSPM.JSPrintManager.websocket_status == JSPM.WSStatus.Blocked) {
            alert('JSPM has blocked this website!');
            return false;
        }
    }

    var wcppPingDelay_ms = 10000; //10 sec

    function wcppDetectOnSuccess() {
        //WCPP utility is installed at the client side
        //redirect to WebClientPrint sample page

        //TIP! You can get the WCPP Version installed through arguments[0]
        alert('Detected!');
        //window.location.href = "URL_TO_SAMPLE_PAGE";
    }

    function wcppDetectOnFailure() {
        //It seems WCPP is not installed at the client side
        //kindly ask the user to install it

        alert('No Detected!');
    }

    //var wcppGetPrintersTimeout_ms = 60000; //60 sec
    //var wcppGetPrintersTimeoutStep_ms = 500; //0.5 sec

    //function wcpGetPrintersOnSuccess() {
    //    // Display client installed printers
    //    if (arguments[0].length > 0) {
    //        var p = arguments[0].split("|");
    //        var options = '';
    //        for (var i = 0; i < p.length; i++) {
    //            options += '<option>' + p[i] + '</option>';
    //        }
    //        $('#installedPrinters').css('visibility', 'visible');
    //        $('#installedPrinterName').html(options);
    //        $('#installedPrinterName').focus();
    //        $('#loadPrinters').hide();
    //    } else {
    //        alert("No printers are installed in your system.");
    //    }
    //}
    //function wcpGetPrintersOnFailure() {
    //    // Do something if printers cannot be got from the client
    //    alert("No printers are installed in your system.");
    //}


</script>

@* WCPP detection script generated by HomeController *@
@Html.Raw(ViewBag.WCPPDetectionScript)
@Html.Raw(ViewBag.WCPScript);
@*@Html.Raw(Neodynamic.SDK.Web.WebClientPrint.CreateScript(Url.Action("PrintFile", "DISR190002", null, Request.Url.Scheme)))*@

@section scripts{
    @* WCPP detection script generated by HomeController *@
    @*@Html.Raw(ViewBag.WCPPDetectionScript)*@
    @*@Html.Raw(ViewBag.WCPScript);*@
    @*@Html.Raw(ViewData["WCPPDetectionScript"]);
        @Html.Raw(ViewData["WCPScript"]);*@
}